channels:
  - defaults
dependencies:
  - dask==0.17.2
  - dask-ml==0.4.1
  - distributed==1.21.4
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - nomkl
  - h5py
  - pip:
    - git+https://github.com/jupyterhub/nbserverproxy
    - graphviz
