name: dask-examples
channels:
  - conda-forge
dependencies:
  # Environment dependencies
  - python=3.9
  # Dask dependencies
  - dask=2022.5.0
  - distributed=2022.5.0
  - dask-image=2021.12.0
  - dask-ml=2022.1.22
  - dask-labextension>=5.2.0
  - nbserverproxy
  # Other pinned dependencies
  - bokeh>=2.4
  - jupyterlab>=3
  - nodejs=16
  - numpy=1.22
  - pandas=1.4
  - ipywidgets=7
  # Avoid heavy MKL dependency
  - nomkl
  # Dependencies for the examples
  - bottleneck
  - dask-xgboost
  - h5py
  - h5py
  - imageio
  - ipympl
  - matplotlib
  - mimesis
  - numba
  - pooch
  - prefect
  - prophet
  - py-xgboost
  - pyarrow
  - python-graphviz
  - rasterio
  - requests
  - scikit-image
  - scikit-learn=1.0
  - seaborn
  - seaborn
  - tpot
  - xarray
  - xgboost
