#!/bin/bash

# Replace DASK_DASHBOARD_URL with the proxy location
sed -i -e "s|DASK_DASHBOARD_URL|/user/${JUPYTERHUB_USER}/proxy/8787|g" binder/jupyterlab-workspace.json

# Temporary workspace workaround
cp binder/jupyterlab-workspace.json /home/jovyan/.jupyter/lab/workspaces/lab-a511.jupyterlab-workspace

exec "$@"
