name: Update Dependencies
on: [push, pull_request]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          environment-file: binder/environment-base.yml
          auto-activate-base: false

      - name: Install dependencies
        run: |
          mamba install nbconvert nbformat jupyter_client ipykernel nbmake pytest

      - name: Execute Notebooks
        run: |
          pytest \
            -vv \
            --nbmake \
            --overwrite \
            --ignore machine-learning/torch-prediction.ipynb \
            --ignore applications/json-data-on-the-web.ipynb
