name: Update Dependencies
on: [push, pull_request]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          auto-activate-base: true
          activate-environment: ""

      - name: Install dependencies
        run: |
          mamba install conda-lock nbconvert nbformat jupyter_client \
          ipykernel nbmake pytest

      - name: Update environment file
        run: |
          conda-lock -f environment-base.yaml -p linux-64
          conda-lock render --kind env conda-lock.yml
          mamba env update -f conda-linux-64.lock.yml
        working-directory: ./binder

      - name: Execute Notebooks
        run: |
          pytest \
            -vv \
            --nbmake \
            --overwrite \
            --ignore machine-learning/torch-prediction.ipynb \
            --ignore applications/json-data-on-the-web.ipynb
